/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import type Anthropic from '@anthropic-ai/sdk';
import { readFileSync } from 'fs';
import { getMediaMime } from '../../../../base/common/mime.js';
import { URI } from '../../../../base/common/uri.js';
import { isAgentFeedbackAnnotationsAttachment, renderAgentFeedbackAnnotationsAttachment } from '../../common/meta/agentFeedbackAttachments.js';
import { isHostSnapshotAttachment } from '../../common/meta/agentSnapshotAttachmentMeta.js';
import { MessageAttachmentKind, type MessageAttachment } from '../../common/state/protocol/state.js';

/**
 * Build the {@link Anthropic.ContentBlockParam}[] payload for an
 * {@link SDKUserMessage} from a plain text prompt and the protocol
 * attachments accompanying the user message.
 *
 * The first block carries the prompt. Image attachments follow as native
 * Anthropic image blocks; the remaining supported attachments are rendered as
 * additional text blocks.
 *
 * Selections are rendered as URI references with an optional line
 * suffix. The protocol's {@link TextSelection} carries range metadata
 * only; the selected text is not included inline.
 *
 * Agent Host normally snapshots embedded images to local `file:` resources
 * before this resolver runs. Embedded images are still accepted as a fallback
 * when that rewrite could not be completed.
 */
export function resolvePromptToContentBlocks(
	prompt: string,
	attachments?: readonly MessageAttachment[],
): Anthropic.ContentBlockParam[] {
	const blocks: Anthropic.ContentBlockParam[] = [{ type: 'text', text: prompt }];
	if (!attachments?.length) {
		return blocks;
	}
	const refLines: string[] = [];
	const imageBlocks: Anthropic.ImageBlockParam[] = [];
	const simpleBlocks: string[] = [];
	const feedbackBlocks: string[] = [];
	for (const att of attachments) {
		if (isAgentFeedbackAnnotationsAttachment(att)) {
			const rendered = renderAgentFeedbackAnnotationsAttachment(att);
			if (rendered) {
				feedbackBlocks.push(rendered);
			}
			continue;
		}
		if (att.type === MessageAttachmentKind.Simple) {
			if (att.modelRepresentation) {
				simpleBlocks.push(att.modelRepresentation);
			}
			continue;
		}
		if (att.type === MessageAttachmentKind.EmbeddedResource) {
			const mediaType = toClaudeImageMediaType(att.contentType);
			if (mediaType) {
				imageBlocks.push(createImageBlock(mediaType, att.data));
			}
			continue;
		}
		if (att.type !== MessageAttachmentKind.Resource) {
			continue;
		}
		const uri = URI.parse(att.uri);
		if (att.displayKind === 'image' && uri.scheme === 'file') {
			const mediaType = toClaudeImageMediaType(getMediaMime(uri.path));
			if (mediaType) {
				imageBlocks.push(createImageBlock(mediaType, readFileSync(uri.fsPath).toString('base64')));
				continue;
			}
		}
		// A host-created snapshot (pasted content, unsaved editor, git: diff, …) is read-only context;
		// annotate the path inline so the model doesn't edit the copy (#331154). This is an advisory
		// signal: the host attachments-dir write-deny only fires for interactive permission prompts, so
		// it does NOT cover Claude's acceptEdits/bypassPermissions/auto modes or subagent inner tools.
		const readonlySuffix = isHostSnapshotAttachment(att) ? ' (read-only snapshot — do not edit this file)' : '';
		if (att.displayKind === 'selection') {
			const startLine = att.selection ? `:${att.selection.range.start.line + 1}` : '';
			refLines.push(`- ${uriToString(uri)}${startLine}${readonlySuffix}`);
		} else {
			refLines.push(`- ${uriToString(uri)}${readonlySuffix}`);
		}
	}
	blocks.push(...imageBlocks);
	if (feedbackBlocks.length > 0) {
		blocks.push({
			type: 'text',
			text: feedbackBlocks.join('\n\n'),
		});
	}
	if (simpleBlocks.length > 0) {
		blocks.push({
			type: 'text',
			text: simpleBlocks.join('\n\n'),
		});
	}
	if (refLines.length === 0) {
		return blocks;
	}
	blocks.push({
		type: 'text',
		text: '<system-reminder>\nThe user provided the following references:\n' +
			refLines.join('\n') +
			'\n\nIMPORTANT: this context may or may not be relevant to your tasks. ' +
			'You should not respond to this context unless it is highly relevant to your task.\n' +
			'</system-reminder>',
	});
	return blocks;
}

type ClaudeImageMediaType = Anthropic.Base64ImageSource['media_type'];

function toClaudeImageMediaType(contentType: string | undefined): ClaudeImageMediaType | undefined {
	switch (contentType) {
		case 'image/jpg':
		case 'image/jpeg':
			return 'image/jpeg';
		case 'image/png':
		case 'image/gif':
		case 'image/webp':
			return contentType;
		default:
			return undefined;
	}
}

function createImageBlock(mediaType: ClaudeImageMediaType, data: string): Anthropic.ImageBlockParam {
	return {
		type: 'image',
		source: {
			type: 'base64',
			media_type: mediaType,
			data,
		},
	};
}

function uriToString(uri: URI): string {
	return uri.scheme === 'file' ? uri.fsPath : uri.toString();
}
